#!/bin/sh
# Sets the dwm bar
# Run by another script every 30 seconds and by the volume increase and decrease script to update volume
sep="|"
xsetroot -name " $(volprint) $sep $(timeprint) $sep $(dateprint) $sep $(islamicdate) "
