#!/bin/sh
# Sets the dwm bar

# To seperate the modules
sep='|'

while true; do
# Prints out the time
time="$( date +"🕐"\ %H:%M )" 

# Prints out the date
date="$(date +"🗓"\ %a","\ %d"th"\ %h\ "'"%y)"

# Print out the volume
volume="🔊 $(pamixer --get-volume)%"

# Sets the bar in one line
# echo "$volume $sep $timedate"
xsetroot -name " $volume $sep $time $sep $date"
sleep 30
done
