#!/bin/zsh
# Just to add undertale to my PATH
exec ~/GOG\ Games/Undertale/start.sh &

# Makes the wasd keys into arrow keys
wasdtoarrow
# Turns them back (checking is on a 10 sec cooldown)
while true; do
    procnum="$(pgrep UNDERTALE)"
    if [[ $procnum = "" ]]; then
        revertwasdtoarrow
        exit 0
    fi
sleep 10
done
