#!/bin/sh
# Just to add undertale to my PATH

# Makes the wasd keys into arrow keys
wasdtoarrow
# Launches game
~/GOG\ Games/Undertale/start.sh
# Reverts wasd to arrow after game process ends
revertwasdtoarrow
